In [1]:
import pandas as pd

acquisitions = pd.read_csv("./data/crunchbase-acquisitions.csv")
acquisitions.head()

,company_permalink,company_name,company_category_code,company_country_code,company_state_code,company_region,company_city,acquirer_permalink,acquirer_name,acquirer_category_code,acquirer_country_code,acquirer_state_code,acquirer_region,acquirer_city,acquired_at,acquired_month,acquired_quarter,acquired_year,price_amount,price_currency_code
0,/company/1000memories,1000memories,web,USA,CA,SF Bay,San Francisco,/company/ancestry-com,Ancestry,ecommerce,USA,UT,Salt Lake City,Provo,10/3/2012,2012-10,2012-Q4,2012,NaN,USD
1,/company/100plus,100Plus,analytics,USA,CA,SF Bay,San Francisco,/company/practice-fusion,Practice Fusion,health,USA,CA,SF Bay,San Francisco,2/27/2013,2013-02,2013-Q1,2013,NaN,USD
2,/company/10best,10best,web,USA,SC,Greenville,Greenville,/company/nile-guide,NileGuide,travel,USA,CA,SF Bay,San Francisco,1/25/2011,2011-01,2011-Q1,2011,NaN,USD
3,/company/10east,10East,network_hosting,USA,FL,Jacksonville,Jacksonville,/company/railcar-management,Railcar Management,enterprise,NaN,NaN,unknown,NaN,4/14/2009,2009-04,2009-Q2,2009,NaN,USD
4,/company/12society,12Society,ecommerce,USA,CA,Los Angeles,West Hollywood,/company/quarterly,Quarterly,web,USA,CA,Los Angeles,West Hollywood,7/3/2013,2013-07,2013-Q3,2013,NaN,USD

In [2]:
companies = pd.read_csv("./data/crunchbase-companies.csv")
companies.head()

,permalink,name,category_code,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at,last_milestone_at
0,/company/waywire,#waywire,news,1750000,operating,USA,NY,New York,New York,1,6/1/2012,2012-06,2012-Q2,2012.0,6/30/2012,6/30/2012,9/6/2013
1,/company/n-plusn,#NAME?,software,600000,operating,USA,NY,New York,New York,1,1/1/2012,2012-01,2012-Q1,2012.0,8/29/2012,8/29/2012,NaN
2,/company/club-domains,.Club Domains,software,7000000,operating,USA,FL,Fort Lauderdale,Oakland Park,1,10/10/2011,2011-10,2011-Q4,2011.0,5/31/2013,5/31/2013,NaN
3,/company/0xdata,0xdata,analytics,1700000,operating,USA,CA,SF Bay,Mountain View,1,NaN,NaN,NaN,NaN,1/3/2013,1/3/2013,1/1/2012
4,/company/1-800-dentist,1-800-DENTIST,health,NaN,operating,USA,CA,Los Angeles,Los Angeles,1,1/1/1986,1986-01,1986-Q1,1986.0,8/19/2010,8/19/2010,8/19/2010

In [4]:
investments = pd.read_csv("./data/crunchbase-investments.csv")
investments.head()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8f in position 3: invalid start byte

In [6]:
rounds = pd.read_csv("./data/crunchbase-rounds.csv")
rounds.head()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa6 in position 4: invalid start byte